[target.'cfg(all(target_arch = "arm", target_os = "none"))']
#runner = "probe-rs run --chip RP2040"
#runner = "elf2uf2-rs --deploy --serial"
#runner = "elf2uf2-rs --deploy"
runner = "make build-binary do-indirect-flash-run"
rustflags = [
  #"-C", "linker=flip-link",
  "-C",
  "link-arg=--nmagic",
  "-C",
  "link-arg=-Tlink.x",
  "-C",
  "link-arg=-Tdefmt.x",

  # Code-size optimizations.
  #   trap unreachable can save a lot of space, but requires nightly compiler.
  #   uncomment the next line if you wish to enable it
  # "-Z", "trap-unreachable=no",
  "-C",
  "inline-threshold=5",
  "-C",
  "no-vectorize-loops",
]

[build]
target = "thumbv6m-none-eabi" # Cortex-M0 and Cortex-M0+
