[target.'cfg(all(target_arch = "arm", target_os = "none"))']
#runner = "probe-rs run --chip RP2040"
runner = "elf2uf2-rs --deploy"
rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tlink-rp.x",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "linker=flip-link",
    "-C", "inline-threshold=5",
    "-C", "no-vectorize-loops",
]
[build]
target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "debug"

[profile.release]
debug = 2